debug: false

# log level 구체적으로 명시
logging:
  level:
    com.com.jongmin.moduleapi: debug
    org.springframework.web.servlet: debug # debug: false 한 다음 따로 이렇게 뽑자
    org.hibernate.type.descriptor.sql.BasicBinder: trace # ? -> Binding Parameter 관찰 가능(개발 단계)

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # 초기 데이터를 생성하겧 할 수 있다. -> data.sql(약속)
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
